version: '3.8'
services:
  bot:
    build: .
    env_file: .env
    depends_on:
      - postgres
    command: python bot.py
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dbname
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
